import * as vscode from 'vscode';

/**
 * Enhanced monitoring for GitHub Copilot and AI-related events
 */
export class CopilotIntegration {
    private voiceManager: any;
    private disposables: vscode.Disposable[] = [];

    constructor(voiceManager: any) {
        this.voiceManager = voiceManager;
        this.setupCopilotMonitoring();
    }

    private setupCopilotMonitoring(): void {
        // Monitor inline completion providers (Copilot suggestions)
        this.monitorInlineCompletions();
        
        // Monitor language model usage (Chat and other AI features)
        this.monitorLanguageModelUsage();
        
        // Monitor code actions that might be AI-generated
        this.monitorCodeActions();
    }

    private monitorInlineCompletions(): void {
        // Listen for text document changes that might indicate Copilot acceptance
        this.disposables.push(
            vscode.workspace.onDidChangeTextDocument(async (event) => {
                // Check if the change looks like a Copilot suggestion acceptance
                if (this.looksLikeCopilotAcceptance(event)) {
                    await this.voiceManager.speak('copilot.accept');
                }
            })
        );

        // Monitor when inline completion providers are triggered
        this.disposables.push(
            vscode.window.onDidChangeTextEditorSelection(async (event) => {
                // This might indicate Copilot suggestion interaction
                if (event.selections.length > 0) {
                    // Debounce rapid selection changes
                    setTimeout(async () => {
                        if (this.mightHaveCopilotSuggestion(event.textEditor)) {
                            await this.voiceManager.speak('copilot.suggestion');
                        }
                    }, 500);
                }
            })
        );
    }

    private monitorLanguageModelUsage(): void {
        // Monitor workspace folder changes
        this.disposables.push(
            vscode.workspace.onDidChangeWorkspaceFolders(() => {
                // This might indicate project changes
                this.voiceManager.speak('workspace.open');
            })
        );

        // Monitor when the active editor changes
        this.disposables.push(
            vscode.window.onDidChangeActiveTextEditor(async (editor) => {
                if (editor && this.documentMightHaveAIContent(editor.document)) {
                    await this.voiceManager.speak('copilot.suggestion');
                }
            })
        );
    }

    private documentMightHaveAIContent(document: vscode.TextDocument): boolean {
        // Simple heuristic to detect if document might have AI-generated content
        const text = document.getText();
        
        // Look for patterns that might indicate AI generation
        const aiPatterns = [
            /\/\/ Generated by/i,
            /\/\* Generated/i,
            /TODO: AI generated/i,
            /Copilot suggestion/i
        ];

        return aiPatterns.some(pattern => pattern.test(text));
    }

    private monitorCodeActions(): void {
        // Monitor when code actions are applied
        this.disposables.push(
            vscode.languages.onDidChangeDiagnostics(async () => {
                // This might indicate code fixes or refactoring
                await this.voiceManager.speak('copilot.suggestion');
            })
        );
    }

    private looksLikeCopilotAcceptance(event: vscode.TextDocumentChangeEvent): boolean {
        // Heuristics to detect Copilot suggestion acceptance
        for (const change of event.contentChanges) {
            // Large insertions might be Copilot suggestions
            if (change.text.length > 20 && change.text.includes('\\n')) {
                return true;
            }
            // Function/method completions
            if (change.text.includes('function') || change.text.includes('=>') || change.text.includes('def ')) {
                return true;
            }
        }
        return false;
    }

    private mightHaveCopilotSuggestion(editor: vscode.TextEditor): boolean {
        // Check if the current context might have triggered Copilot
        const position = editor.selection.active;
        const line = editor.document.lineAt(position.line);
        
        // Common patterns that trigger Copilot
        const triggerPatterns = [
            /^\\s*\/\//, // Comments
            /^\\s*function/, // Function declarations
            /^\\s*const/, // Variable declarations
            /^\\s*class/, // Class declarations
            /^\\s*if/, // Conditional statements
            /^\\s*for/, // Loops
            /^\\s*import/, // Imports
        ];

        return triggerPatterns.some(pattern => pattern.test(line.text));
    }

    public dispose(): void {
        this.disposables.forEach(d => d.dispose());
    }
}